###
//Register User

POST http://localhost:4000/api/v2/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123",
    "confirmPassword": "test123"
}

###
GET http://localhost:4000/api/v2/auth/verify/aab5a34b91b677ec9b3e610006efde5b34d393406affe95c2651afd872eb8fba

###
//User Login

POST http://localhost:4000/api/v2/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}

###
//user profile

GET http://localhost:4000/api/v2/profile


###
//post a summary

POST http://localhost:4000/api/v2/summary/save
Content-Type: application/json

{
  "text": "Get it right in the forest, write a poem for this passage",
  "wordCount": 700
}

###
//get summary text

GET http://localhost:4000/api/v2/summary/10


###
//get quote balance

GET http://localhost:4000/api/v2/balance